import { NextRequest, NextResponse } from "next/server";
import { getNeo4jDriver } from "@/lib/neo4j";
import OpenAI from "openai";

// Helper to format/clean Cypher queries generated by LLMs
function cleanCypherQuery(query: string): string {
  // 1. Try to extract from a code block if the LLM provided one
  const codeBlockMatch = query.match(/```(?:cypher)?\n?([\s\S]*?)```/i);
  let cleaned = codeBlockMatch ? codeBlockMatch[1] : query;

  // 2. Remove common prefixes
  cleaned = cleaned.replace(/^\*\*cypher\s*query:?\*\*/i, "").trim();
  cleaned = cleaned.replace(/^cypher\s*query:?/i, "").trim();

  // 3. Remove everything from "**Explanation**" or "Explanation:" onwards
  const explMatch = cleaned.match(/(?:\*\*Explanation\*\*|Explanation:)/i);
  if (explMatch && explMatch.index !== undefined) {
    cleaned = cleaned.substring(0, explMatch.index);
  }

  // 4. Strip out comment lines and empty lines
  const lines = cleaned.split("\n");
  const cypherLines = lines.filter(line => !line.trim().startsWith("//") && line.trim().length > 0);
  
  return cypherLines.join("\n").trim();
}

const SCHEMA_TEXT = `
Node properties are the following:
- Customer: id (STRING), name (STRING), industry (STRING), tier (STRING), health_score (INTEGER)
- Product: id (STRING), name (STRING), category (STRING), monthly_price (INTEGER)
- Contract: id (STRING), type (STRING), value (INTEGER), renewal_date (STRING), status (STRING)
- SupportCase: id (STRING), title (STRING), priority (STRING), status (STRING), created_at (STRING)

Relationship types are the following:
- (:Customer)-[:OWNS]->(:Product)
- (:Customer)-[:HAS_CONTRACT]->(:Contract)
- (:Customer)-[:OPENED]->(:SupportCase)
`;

export async function POST(req: NextRequest) {
  try {
    const { question } = await req.json();
    if (!question) {
      return NextResponse.json({ error: "Missing question parameter" }, { status: 400 });
    }

    const apiKey = process.env.LLM_API_KEY;
    const baseURL = process.env.LLM_BASE_URL;
    const modelName = process.env.LLM_MODEL_NAME || "gpt-oss-120b";

    if (!apiKey) {
      return NextResponse.json({ error: "LLM_API_KEY is not configured" }, { status: 500 });
    }

    const openai = new OpenAI({
      apiKey,
      baseURL,
    });

    // ── Phase 1: Cypher Generation ──────────────────────────────────────────
    const cypherPrompt = `Task: Generate a Cypher query to query a Neo4j graph database.
Instructions:
Use only the relationship types and properties provided in the schema.
Do not use any other relationship types or properties that are not in the schema.

Neo4j 5+ Syntax Constraints:
- NEVER use size(node) (e.g., size(sc) or size(c)). This is invalid in Neo4j 5 and causes a syntax error.
- To count nodes or relationship matches, use count() (e.g. count(sc)).
- Alternatively, count pattern matches using size() with a list comprehension or path pattern (e.g., size([(c)-[:OPENED]->(sc:SupportCase) | sc])).
- For counting support cases or relationships, prefer count(sc) or count(r).

Schema Definitions:
- A customer is "at risk of renewal" if they have a contract with status = 'At Risk' or a low health score (health_score < 50).
- Check both: MATCH (c:Customer)-[:HAS_CONTRACT]->(ct:Contract) WHERE ct.status = 'At Risk' OR c.health_score < 50

Schema:
${SCHEMA_TEXT}

Question: ${question}
Cypher Query (RETURN ONLY THE CYPHER QUERY. DO NOT INCLUDE MARKDOWN, EXPLANATIONS, OR ANY OTHER TEXT):`;

    const cypherResponse = await openai.chat.completions.create({
      model: modelName,
      messages: [{ role: "user", content: cypherPrompt }],
      temperature: 0,
    });

    const rawCypher = cypherResponse.choices[0]?.message?.content || "";
    const cypherQuery = cleanCypherQuery(rawCypher);

    console.log("Generated Cypher Query:", cypherQuery);

    // ── Phase 2: Query Execution ─────────────────────────────────────────────
    const driver = getNeo4jDriver();
    const session = driver.session();
    let rawResults: Record<string, any>[] = [];

    try {
      const dbResult = await session.run(cypherQuery);
      rawResults = dbResult.records.map((record) => {
        const rowObject: Record<string, any> = {};
        for (const key of record.keys) {
          const value = record.get(key);
          const k = String(key);
          // Serialize Neo4j numbers/integers if they have helper methods, or keep as is
          if (value && typeof value === "object" && "low" in value && "high" in value) {
            rowObject[k] = (value as any).low; // handle Neo4j Integer type
          } else if (value && typeof value === "object" && "properties" in value) {
            rowObject[k] = (value as any).properties; // extract properties for nodes/relationships
          } else {
            rowObject[k] = value;
          }
        }
        return rowObject;
      });
    } catch (dbError) {
      console.error("Database execution failed for query:", cypherQuery, dbError);
      return NextResponse.json({
        answer: `I generated a Cypher query but encountered an error running it against the database: ${dbError instanceof Error ? dbError.message : "Unknown database error"}.`,
        source: {
          cypher_query: cypherQuery,
          raw_results: [],
        }
      });
    } finally {
      await session.close();
    }

    // ── Phase 3: Final Answer Generation ──────────────────────────────────────
    const answerPrompt = `Task: You are an assistant that translates database query results into clear, user-friendly, and professional natural language responses.
Question: ${question}
Cypher Query: ${cypherQuery}
Query Results: ${JSON.stringify(rawResults)}

Instructions:
- Formulate a clean, natural response to the user's question using the provided Query Results.
- If the query results are empty or null, state clearly that no matching information was found.
- Keep the answer concise, helpful, and business-focused.
- Do not mention technical implementation details like 'Cypher query', 'Neo4j', or 'database fields' in the final response unless directly asked.`;

    const answerResponse = await openai.chat.completions.create({
      model: modelName,
      messages: [{ role: "user", content: answerPrompt }],
      temperature: 0,
    });

    const answer = answerResponse.choices[0]?.message?.content || "No answer generated.";

    return NextResponse.json({
      answer,
      source: {
        cypher_query: cypherQuery,
        raw_results: rawResults,
      },
    });

  } catch (error) {
    console.error("API Chat execution failed:", error);
    let errorMessage = error instanceof Error ? error.message : "Internal Server Error";
    
    // Provide a friendlier message for Cerebras/OpenAI rate limits
    if (errorMessage.includes("429")) {
      errorMessage = "The AI service is currently experiencing high traffic (Rate Limit Exceeded). Please wait a moment and try again.";
    }

    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    );
  }
}
